services:
  train:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
